### ISSUE TITLE
[dev] Checklist mise en place

### ISSUE THREAD

**Issue by statnmap** [balglave/FishMap#6]
- [x] Remplir les Key Dates et le calendrier prévisionnel
- [x] Ajouter chaque utilisateur au projet en tant que "Guest"
- [x] Prévenir les chefs de projets de monter le niveau de Notification à "Watch" sur la page d'acceuil du projet pour recevoir toutes les notifications
- [x] S'assurer que le Board est pret: https://github.com/users/balglave/projects/1/views/1
- [x] S'assurer que le Wiki Home est pret: https://github.com/balglave/FishMap/wiki/Home
- [x] Indiquer aussi la méthode de partage de CR dans l'issue de Bienvenue du Client : https://github.com/balglave/FishMap/issues/4
- [x] Notifier chaque utilisateur en les mentionnant dans un commentaire de l'issue : https://github.com/balglave/FishMap/issues/4 avec le texte suivant : 
```
Merci de bien vouloir lire et valider le contenu de cette page.
Si vous lisez ce message dans un email, vous pouvez cliquer sur le lien suivant pour accéder à la page :
https://github.com/balglave/FishMap/issues/4
@mention, @mention, ...
```

- [ ] ~~Mettre en place {renv} en suivant "dev/dev_history_renv.R"~~
- [x] Si nécessaires, exécuter les étapes de "dev/dev_history.R". La plupart sont déja faites.

**Comment by statnmap** [comment]
Done.  
Infos are in issue #1
